# safelist
branches:
  only:
  - master
before_install:
  - gem install cocoapods
  - pod repo update
language: objective-c
osx_image: xcode10.1
script:
  - xcodebuild clean test -workspace bacon.xcworkspace -scheme bacon -destination "platform=iOS Simulator,name=iPhone 7,OS=12.1" -quiet | xcpretty
