before_install:
  - gem install cocoapods
language: objective-c
osx_image: xcode10.1
xcode_project: bacon.xcodeproj
xcode_scheme: bacon
xcode_destination: platform=iOS Simulator, OS=12.1, name=iPad Pro (9.7-inch)
